# Manipulating NumPy arrays
## Views and copies

In [1]:
import numpy as np

In [2]:
mi_casa = np.array([-45, 11, 34, 22, 75, -62, 0, 4])

In [3]:
su_casa = mi_casa

**Same or different**

In [4]:
# reference equality
mi_casa is su_casa

True

In [5]:
id(mi_casa)

4600714064

In [6]:
id(su_casa)

4600714064

In [7]:
# value equality
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [8]:
su_casa[4] = 1024 

In [9]:
su_casa

array([ -45,   11,   34,   22, 1024,  -62,    0,    4])

In [10]:
mi_casa

array([ -45,   11,   34,   22, 1024,  -62,    0,    4])

In [11]:
tree_house = np.array([-45, 11, 34, 22, 75, -62, 0, 4])

In [12]:
tree_house == su_casa

array([ True,  True,  True,  True, False,  True,  True,  True])

In [13]:
id(tree_house)

4600715104

In [14]:
id(mi_casa)

4600714064

In [15]:
tree_house[0] = 10000
tree_house

array([10000,    11,    34,    22,    75,   -62,     0,     4])

In [16]:
mi_casa

array([ -45,   11,   34,   22, 1024,  -62,    0,    4])

In [17]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True])

In [18]:
tree_house is mi_casa

False

### View: a shallow copy

In [19]:
farm_house = tree_house.view()
farm_house.shape = (2, 4)

In [20]:
tree_house

array([10000,    11,    34,    22,    75,   -62,     0,     4])

In [21]:
farm_house

array([[10000,    11,    34,    22],
       [   75,   -62,     0,     4]])

In [22]:
tree_house[3] = -999
farm_house

array([[10000,    11,    34,  -999],
       [   75,   -62,     0,     4]])

### Deep copy

In [23]:
dog_house = np.copy(tree_house)
dog_house[0] = -1212
dog_house

array([-1212,    11,    34,  -999,    75,   -62,     0,     4])

In [24]:
tree_house

array([10000,    11,    34,  -999,    75,   -62,     0,     4])

## Array attributes

In [25]:
a = np.array(np.arange(24)).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
a.ndim

3

In [27]:
a.shape

(2, 3, 4)

In [28]:
a.size

24

In [29]:
a.dtype

dtype('int64')

In [30]:
a.itemsize # a 64 bit int is of size 8 bytes

8

In [31]:
type(a)

numpy.ndarray

## Add and remove elements

In [32]:
a = np.array(np.arange(24)).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [33]:
b = np.append(a, [5, 6, 7, 8])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [34]:
b.shape

(28,)

In [35]:
b.reshape((7, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [36]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
c = np.array(np.arange(24)).reshape((2,3,4))*10 + 3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [38]:
np.append(a, c, axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [39]:
np.append(a, c, axis=0).shape

(4, 3, 4)

In [40]:
np.append(a, c, axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [41]:
np.append(a, c, axis=1).shape

(2, 6, 4)

In [42]:
np.append(a, c, axis=2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [43]:
np.append(a, c, axis=2).shape

(2, 3, 8)

In [44]:
my_hay_stack = np.hstack((a,c))
my_hay_stack

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [45]:
my_hay_stack[0,0,2] = 999

In [46]:
my_hay_stack

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [47]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [49]:
after_insert_array = np.insert(c, 1, 444, axis=0)
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [50]:
np.insert(c, 1, 444, axis=1)

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [51]:
np.insert(c, 1, 444, axis=2)

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

In [52]:
d = np.empty(c.shape)
np.copyto(d, c)
d

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [53]:
np.delete(d, 1, axis=0)

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]]])

In [54]:
np.delete(d, 1, axis=1)

array([[[  3.,  13.,  23.,  33.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [203., 213., 223., 233.]]])

In [55]:
np.delete(d, 1, axis=2)

array([[[  3.,  23.,  33.],
        [ 43.,  63.,  73.],
        [ 83., 103., 113.]],

       [[123., 143., 153.],
        [163., 183., 193.],
        [203., 223., 233.]]])

## Join and split arrays

In [56]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [57]:
b

array([[5, 6]])

In [58]:
together = np.concatenate((a, b), axis=0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
together.shape

(3, 2)

In [60]:
together[1, 1] = 555
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [61]:
c = np.array([[1, 2], [3, 4]])*3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [62]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [63]:
arrays = np.zeros((5, 3, 4))
for n in range(5):
    arrays[n] = np.random.randn(3,4)
    
arrays

array([[[ 0.93915801, -0.24933026, -0.29921203, -0.38139105],
        [-0.8319712 ,  0.29718042, -0.47314615,  0.75326959],
        [-1.01164588,  0.00979498,  1.29304442,  0.26462192]],

       [[ 1.09054465,  0.77009971, -1.05822269, -0.82988402],
        [-0.3844342 , -0.32723408, -0.16776535,  0.75153285],
        [-0.53928187,  0.56378858,  1.12671995,  1.05869568]],

       [[ 0.55858536, -1.96936318,  1.77288819,  0.68880633],
        [ 1.17471967,  1.54612158, -1.24937676,  0.35203266],
        [-0.58399244, -0.8207327 , -1.96792272, -0.17218015]],

       [[-2.76719555, -0.33987409, -1.61009029,  0.63939689],
        [-2.65711767, -0.35066246,  0.92321334,  1.66910058],
        [ 0.68393499, -0.66631955,  0.11986789,  0.7082282 ]],

       [[ 1.08977193, -0.88563772, -0.03167445, -0.04087943],
        [ 0.34625046,  1.1216175 ,  0.23311113, -0.32570197],
        [-1.25190676, -1.84778934,  0.15105059, -1.3128387 ]]])

In [64]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [65]:
stack0

array([[[ 0.93915801, -0.24933026, -0.29921203, -0.38139105],
        [-0.8319712 ,  0.29718042, -0.47314615,  0.75326959],
        [-1.01164588,  0.00979498,  1.29304442,  0.26462192]],

       [[ 1.09054465,  0.77009971, -1.05822269, -0.82988402],
        [-0.3844342 , -0.32723408, -0.16776535,  0.75153285],
        [-0.53928187,  0.56378858,  1.12671995,  1.05869568]],

       [[ 0.55858536, -1.96936318,  1.77288819,  0.68880633],
        [ 1.17471967,  1.54612158, -1.24937676,  0.35203266],
        [-0.58399244, -0.8207327 , -1.96792272, -0.17218015]],

       [[-2.76719555, -0.33987409, -1.61009029,  0.63939689],
        [-2.65711767, -0.35066246,  0.92321334,  1.66910058],
        [ 0.68393499, -0.66631955,  0.11986789,  0.7082282 ]],

       [[ 1.08977193, -0.88563772, -0.03167445, -0.04087943],
        [ 0.34625046,  1.1216175 ,  0.23311113, -0.32570197],
        [-1.25190676, -1.84778934,  0.15105059, -1.3128387 ]]])

In [66]:
stack1

array([[[ 0.93915801, -0.24933026, -0.29921203, -0.38139105],
        [ 1.09054465,  0.77009971, -1.05822269, -0.82988402],
        [ 0.55858536, -1.96936318,  1.77288819,  0.68880633],
        [-2.76719555, -0.33987409, -1.61009029,  0.63939689],
        [ 1.08977193, -0.88563772, -0.03167445, -0.04087943]],

       [[-0.8319712 ,  0.29718042, -0.47314615,  0.75326959],
        [-0.3844342 , -0.32723408, -0.16776535,  0.75153285],
        [ 1.17471967,  1.54612158, -1.24937676,  0.35203266],
        [-2.65711767, -0.35066246,  0.92321334,  1.66910058],
        [ 0.34625046,  1.1216175 ,  0.23311113, -0.32570197]],

       [[-1.01164588,  0.00979498,  1.29304442,  0.26462192],
        [-0.53928187,  0.56378858,  1.12671995,  1.05869568],
        [-0.58399244, -0.8207327 , -1.96792272, -0.17218015],
        [ 0.68393499, -0.66631955,  0.11986789,  0.7082282 ],
        [-1.25190676, -1.84778934,  0.15105059, -1.3128387 ]]])

In [67]:
stack2

array([[[ 0.93915801,  1.09054465,  0.55858536, -2.76719555,
          1.08977193],
        [-0.24933026,  0.77009971, -1.96936318, -0.33987409,
         -0.88563772],
        [-0.29921203, -1.05822269,  1.77288819, -1.61009029,
         -0.03167445],
        [-0.38139105, -0.82988402,  0.68880633,  0.63939689,
         -0.04087943]],

       [[-0.8319712 , -0.3844342 ,  1.17471967, -2.65711767,
          0.34625046],
        [ 0.29718042, -0.32723408,  1.54612158, -0.35066246,
          1.1216175 ],
        [-0.47314615, -0.16776535, -1.24937676,  0.92321334,
          0.23311113],
        [ 0.75326959,  0.75153285,  0.35203266,  1.66910058,
         -0.32570197]],

       [[-1.01164588, -0.53928187, -0.58399244,  0.68393499,
         -1.25190676],
        [ 0.00979498,  0.56378858, -0.8207327 , -0.66631955,
         -1.84778934],
        [ 1.29304442,  1.12671995, -1.96792272,  0.11986789,
          0.15105059],
        [ 0.26462192,  1.05869568, -0.17218015,  0.7082282 ,
         -1

In [68]:
temp = np.arange(5)
np.split(temp, 1)

[array([0, 1, 2, 3, 4])]

In [69]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [70]:
s0 = np.split(before_split, 5, axis=0)
s0

[array([[[ 0.93915801, -0.24933026, -0.29921203, -0.38139105],
         [-0.8319712 ,  0.29718042, -0.47314615,  0.75326959],
         [-1.01164588,  0.00979498,  1.29304442,  0.26462192]]]),
 array([[[ 1.09054465,  0.77009971, -1.05822269, -0.82988402],
         [-0.3844342 , -0.32723408, -0.16776535,  0.75153285],
         [-0.53928187,  0.56378858,  1.12671995,  1.05869568]]]),
 array([[[ 0.55858536, -1.96936318,  1.77288819,  0.68880633],
         [ 1.17471967,  1.54612158, -1.24937676,  0.35203266],
         [-0.58399244, -0.8207327 , -1.96792272, -0.17218015]]]),
 array([[[-2.76719555, -0.33987409, -1.61009029,  0.63939689],
         [-2.65711767, -0.35066246,  0.92321334,  1.66910058],
         [ 0.68393499, -0.66631955,  0.11986789,  0.7082282 ]]]),
 array([[[ 1.08977193, -0.88563772, -0.03167445, -0.04087943],
         [ 0.34625046,  1.1216175 ,  0.23311113, -0.32570197],
         [-1.25190676, -1.84778934,  0.15105059, -1.3128387 ]]])]

In [71]:
type(s0)

list

In [72]:
s0[1]

array([[[ 1.09054465,  0.77009971, -1.05822269, -0.82988402],
        [-0.3844342 , -0.32723408, -0.16776535,  0.75153285],
        [-0.53928187,  0.56378858,  1.12671995,  1.05869568]]])

In [73]:
s0[1].shape

(1, 3, 4)

In [74]:
s1 = np.split(before_split, 3, axis=1)
s1

[array([[[ 0.93915801, -0.24933026, -0.29921203, -0.38139105]],
 
        [[ 1.09054465,  0.77009971, -1.05822269, -0.82988402]],
 
        [[ 0.55858536, -1.96936318,  1.77288819,  0.68880633]],
 
        [[-2.76719555, -0.33987409, -1.61009029,  0.63939689]],
 
        [[ 1.08977193, -0.88563772, -0.03167445, -0.04087943]]]),
 array([[[-0.8319712 ,  0.29718042, -0.47314615,  0.75326959]],
 
        [[-0.3844342 , -0.32723408, -0.16776535,  0.75153285]],
 
        [[ 1.17471967,  1.54612158, -1.24937676,  0.35203266]],
 
        [[-2.65711767, -0.35066246,  0.92321334,  1.66910058]],
 
        [[ 0.34625046,  1.1216175 ,  0.23311113, -0.32570197]]]),
 array([[[-1.01164588,  0.00979498,  1.29304442,  0.26462192]],
 
        [[-0.53928187,  0.56378858,  1.12671995,  1.05869568]],
 
        [[-0.58399244, -0.8207327 , -1.96792272, -0.17218015]],
 
        [[ 0.68393499, -0.66631955,  0.11986789,  0.7082282 ]],
 
        [[-1.25190676, -1.84778934,  0.15105059, -1.3128387 ]]])]

In [75]:
s2 = np.split(before_split, 4, axis=2)
s2

[array([[[ 0.93915801],
         [-0.8319712 ],
         [-1.01164588]],
 
        [[ 1.09054465],
         [-0.3844342 ],
         [-0.53928187]],
 
        [[ 0.55858536],
         [ 1.17471967],
         [-0.58399244]],
 
        [[-2.76719555],
         [-2.65711767],
         [ 0.68393499]],
 
        [[ 1.08977193],
         [ 0.34625046],
         [-1.25190676]]]), array([[[-0.24933026],
         [ 0.29718042],
         [ 0.00979498]],
 
        [[ 0.77009971],
         [-0.32723408],
         [ 0.56378858]],
 
        [[-1.96936318],
         [ 1.54612158],
         [-0.8207327 ]],
 
        [[-0.33987409],
         [-0.35066246],
         [-0.66631955]],
 
        [[-0.88563772],
         [ 1.1216175 ],
         [-1.84778934]]]), array([[[-0.29921203],
         [-0.47314615],
         [ 1.29304442]],
 
        [[-1.05822269],
         [-0.16776535],
         [ 1.12671995]],
 
        [[ 1.77288819],
         [-1.24937676],
         [-1.96792272]],
 
        [[-1.61009029],
   

## Array shape manipulation
### reshape

In [76]:
my_start_array = np.array(np.arange(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [77]:
my_start_array.shape

(24,)

In [78]:
my_3_8_array = my_start_array.reshape((3, 8))
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [79]:
my_3_8_array[0, 0] = 1234
my_start_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [80]:
# reshape created a view of the original array

In [81]:
my_ravel_array = my_3_8_array.ravel()
my_ravel_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [82]:
my_ravel_array.shape

(24,)

In [83]:
for n in my_3_8_array.flat:
    print(n)

1234
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## Rearrange array elements

In [84]:
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_start_array.reshape((2, 3, 4))

In [85]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [86]:
np.fliplr(my_3_8_array)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [87]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [88]:
np.fliplr(my_2_3_4_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [89]:
np.flipud(my_3_8_array)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [90]:
np.flipud(my_2_3_4_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [91]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [92]:
np.roll(my_start_array, 5)

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [93]:
np.roll(my_start_array, -5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23,  0,  1,  2,  3,  4])

In [94]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [95]:
np.roll(my_2_3_4_array, 2)

array([[[22, 23,  0,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]]])

In [96]:
np.roll(my_2_3_4_array, -2)

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23,  0,  1]]])

In [97]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [98]:
np.rot90(my_3_8_array )

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [99]:
np.rot90(my_3_8_array, k=-1)

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])

## Transpose like operation

In [100]:
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_start_array.reshape((2, 3, 4))

In [101]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [102]:
np.transpose(my_start_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [103]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [104]:
np.transpose(my_3_8_array)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [105]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [106]:
np.transpose(my_2_3_4_array, axes=(0,2,1))

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [107]:
np.swapaxes(my_2_3_4_array, 1, 0)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [108]:
np.rollaxis(my_2_3_4_array, 0, 2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

* Use `np.transpose` to permute all the axes one
* Use `np.swapaxes` to swap any two axes
* Use `np.rollaxis` to "rotate" the axes

## Tiling arrays

In [109]:
my_start_array = np.array(np.arange(12))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [110]:
np.tile(my_start_array, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [111]:
np.tile(my_start_array, 3).reshape((3, 12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [112]:
my_second_array = np.array(np.arange(7))
my_second_array

array([0, 1, 2, 3, 4, 5, 6])

In [113]:
tile_1 = np.tile(my_second_array, (3, 1))
tile_1

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [114]:
tile_2 = np.tile(tile_1, (2, 2))
tile_2

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

In [115]:
tile_3 = np.tile(tile_2, (3, 1))
tile_3

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

In [116]:
my_second_array

array([0, 1, 2, 3, 4, 5, 6])

In [117]:
np.repeat(my_second_array, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [118]:
my_repeatable_array = np.array(np.arange(24)).reshape(2,3,4)
my_repeatable_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [119]:
np.repeat(my_repeatable_array, 2, axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [120]:
np.repeat(my_repeatable_array, 2, axis=1)

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [20, 21, 22, 23]]])

In [121]:
np.repeat(my_repeatable_array, 2, axis=2)

array([[[ 0,  0,  1,  1,  2,  2,  3,  3],
        [ 4,  4,  5,  5,  6,  6,  7,  7],
        [ 8,  8,  9,  9, 10, 10, 11, 11]],

       [[12, 12, 13, 13, 14, 14, 15, 15],
        [16, 16, 17, 17, 18, 18, 19, 19],
        [20, 20, 21, 21, 22, 22, 23, 23]]])