# Manipulating NumPy arrays
## Views and copies

In [1]:
import numpy as np

In [2]:
mi_casa = np.array([-45, 11, 34, 22, 75, -62, 0, 4])

In [3]:
su_casa = mi_casa

**Same or different**

In [4]:
# reference equality
mi_casa is su_casa

True

In [5]:
id(mi_casa)

4447913744

In [6]:
id(su_casa)

4447913744

In [7]:
# value equality
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [8]:
su_casa[4] = 1024 

In [9]:
su_casa

array([ -45,   11,   34,   22, 1024,  -62,    0,    4])

In [10]:
mi_casa

array([ -45,   11,   34,   22, 1024,  -62,    0,    4])

In [11]:
tree_house = np.array([-45, 11, 34, 22, 75, -62, 0, 4])

In [12]:
tree_house == su_casa

array([ True,  True,  True,  True, False,  True,  True,  True])

In [13]:
id(tree_house)

4447995024

In [14]:
id(mi_casa)

4447913744

In [15]:
tree_house[0] = 10000
tree_house

array([10000,    11,    34,    22,    75,   -62,     0,     4])

In [16]:
mi_casa

array([ -45,   11,   34,   22, 1024,  -62,    0,    4])

In [17]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True])

In [18]:
tree_house is mi_casa

False

### View: a shallow copy

In [19]:
farm_house = tree_house.view()
farm_house.shape = (2, 4)

In [20]:
tree_house

array([10000,    11,    34,    22,    75,   -62,     0,     4])

In [21]:
farm_house

array([[10000,    11,    34,    22],
       [   75,   -62,     0,     4]])

In [22]:
tree_house[3] = -999
farm_house

array([[10000,    11,    34,  -999],
       [   75,   -62,     0,     4]])

### Deep copy

In [23]:
dog_house = np.copy(tree_house)
dog_house[0] = -1212
dog_house

array([-1212,    11,    34,  -999,    75,   -62,     0,     4])

In [24]:
tree_house

array([10000,    11,    34,  -999,    75,   -62,     0,     4])

## Array attributes

In [25]:
a = np.array(np.arange(24)).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
a.ndim

3

In [27]:
a.shape

(2, 3, 4)

In [28]:
a.size

24

In [29]:
a.dtype

dtype('int64')

In [30]:
a.itemsize # a 64 bit int is of size 8 bytes

8

In [31]:
type(a)

numpy.ndarray

## Add and remove elements

In [32]:
a = np.array(np.arange(24)).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [33]:
b = np.append(a, [5, 6, 7, 8])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [34]:
b.shape

(28,)

In [35]:
b.reshape((7, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [36]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
c = np.array(np.arange(24)).reshape((2,3,4))*10 + 3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [38]:
np.append(a, c, axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [39]:
np.append(a, c, axis=0).shape

(4, 3, 4)

In [40]:
np.append(a, c, axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [41]:
np.append(a, c, axis=1).shape

(2, 6, 4)

In [42]:
np.append(a, c, axis=2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [43]:
np.append(a, c, axis=2).shape

(2, 3, 8)

In [45]:
my_hay_stack = np.hstack((a,c))
my_hay_stack

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [46]:
my_hay_stack[0,0,2] = 999

In [47]:
my_hay_stack

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [48]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [49]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [50]:
after_insert_array = np.insert(c, 1, 444, axis=0)
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [51]:
np.insert(c, 1, 444, axis=1)

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [53]:
np.insert(c, 1, 444, axis=2)

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

In [54]:
d = np.empty(c.shape)
np.copyto(d, c)
d

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [55]:
np.delete(d, 1, axis=0)

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]]])

In [56]:
np.delete(d, 1, axis=1)

array([[[  3.,  13.,  23.,  33.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [203., 213., 223., 233.]]])

In [57]:
np.delete(d, 1, axis=2)

array([[[  3.,  23.,  33.],
        [ 43.,  63.,  73.],
        [ 83., 103., 113.]],

       [[123., 143., 153.],
        [163., 183., 193.],
        [203., 223., 233.]]])

## Join and split arrays

In [60]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [61]:
b

array([[5, 6]])

In [63]:
together = np.concatenate((a, b), axis=0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
together.shape

(3, 2)

In [65]:
together[1, 1] = 555
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [66]:
c = np.array([[1, 2], [3, 4]])*3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [67]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [71]:
arrays = np.zeros((5, 3, 4))
for n in range(5):
    arrays[n] = np.random.randn(3,4)
    
arrays

array([[[ 0.42711362,  2.13059943,  1.00668329, -1.16284069],
        [-2.35899144, -0.80764104,  0.30297251,  0.48409107],
        [-0.26014634,  0.82748868, -0.8690082 ,  1.4246587 ]],

       [[ 2.58018343,  1.37196985,  0.41966824, -0.65883572],
        [ 1.15267943,  0.93067746,  0.35353256,  1.71039414],
        [ 0.37644574,  0.21687124, -1.55216387, -0.27160831]],

       [[ 1.58161786, -0.81689155, -2.38956119, -1.0290985 ],
        [ 0.53990218, -0.46179142, -2.3284667 ,  1.03600742],
        [-0.15247791, -0.46434394, -0.96841871,  2.21144516]],

       [[-1.07131578,  0.07473873,  0.06633345, -0.45480478],
        [-1.36677173,  0.03374325,  0.87855698,  0.96613826],
        [ 0.55155076,  1.39285747,  0.31524593, -2.47357217]],

       [[ 0.05988685, -0.30591724,  0.41864608,  0.08106728],
        [-0.54590614, -0.75059878, -0.25141236, -2.21965157],
        [ 1.0724355 ,  0.19341328, -1.08585181, -1.38498778]]])

In [72]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [73]:
stack0

array([[[ 0.42711362,  2.13059943,  1.00668329, -1.16284069],
        [-2.35899144, -0.80764104,  0.30297251,  0.48409107],
        [-0.26014634,  0.82748868, -0.8690082 ,  1.4246587 ]],

       [[ 2.58018343,  1.37196985,  0.41966824, -0.65883572],
        [ 1.15267943,  0.93067746,  0.35353256,  1.71039414],
        [ 0.37644574,  0.21687124, -1.55216387, -0.27160831]],

       [[ 1.58161786, -0.81689155, -2.38956119, -1.0290985 ],
        [ 0.53990218, -0.46179142, -2.3284667 ,  1.03600742],
        [-0.15247791, -0.46434394, -0.96841871,  2.21144516]],

       [[-1.07131578,  0.07473873,  0.06633345, -0.45480478],
        [-1.36677173,  0.03374325,  0.87855698,  0.96613826],
        [ 0.55155076,  1.39285747,  0.31524593, -2.47357217]],

       [[ 0.05988685, -0.30591724,  0.41864608,  0.08106728],
        [-0.54590614, -0.75059878, -0.25141236, -2.21965157],
        [ 1.0724355 ,  0.19341328, -1.08585181, -1.38498778]]])

In [74]:
stack1

array([[[ 0.42711362,  2.13059943,  1.00668329, -1.16284069],
        [ 2.58018343,  1.37196985,  0.41966824, -0.65883572],
        [ 1.58161786, -0.81689155, -2.38956119, -1.0290985 ],
        [-1.07131578,  0.07473873,  0.06633345, -0.45480478],
        [ 0.05988685, -0.30591724,  0.41864608,  0.08106728]],

       [[-2.35899144, -0.80764104,  0.30297251,  0.48409107],
        [ 1.15267943,  0.93067746,  0.35353256,  1.71039414],
        [ 0.53990218, -0.46179142, -2.3284667 ,  1.03600742],
        [-1.36677173,  0.03374325,  0.87855698,  0.96613826],
        [-0.54590614, -0.75059878, -0.25141236, -2.21965157]],

       [[-0.26014634,  0.82748868, -0.8690082 ,  1.4246587 ],
        [ 0.37644574,  0.21687124, -1.55216387, -0.27160831],
        [-0.15247791, -0.46434394, -0.96841871,  2.21144516],
        [ 0.55155076,  1.39285747,  0.31524593, -2.47357217],
        [ 1.0724355 ,  0.19341328, -1.08585181, -1.38498778]]])

In [75]:
stack2

array([[[ 0.42711362,  2.58018343,  1.58161786, -1.07131578,
          0.05988685],
        [ 2.13059943,  1.37196985, -0.81689155,  0.07473873,
         -0.30591724],
        [ 1.00668329,  0.41966824, -2.38956119,  0.06633345,
          0.41864608],
        [-1.16284069, -0.65883572, -1.0290985 , -0.45480478,
          0.08106728]],

       [[-2.35899144,  1.15267943,  0.53990218, -1.36677173,
         -0.54590614],
        [-0.80764104,  0.93067746, -0.46179142,  0.03374325,
         -0.75059878],
        [ 0.30297251,  0.35353256, -2.3284667 ,  0.87855698,
         -0.25141236],
        [ 0.48409107,  1.71039414,  1.03600742,  0.96613826,
         -2.21965157]],

       [[-0.26014634,  0.37644574, -0.15247791,  0.55155076,
          1.0724355 ],
        [ 0.82748868,  0.21687124, -0.46434394,  1.39285747,
          0.19341328],
        [-0.8690082 , -1.55216387, -0.96841871,  0.31524593,
         -1.08585181],
        [ 1.4246587 , -0.27160831,  2.21144516, -2.47357217,
         -1

In [76]:
temp = np.arange(5)
np.split(temp, 1)

[array([0, 1, 2, 3, 4])]

In [86]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [87]:
s0 = np.split(before_split, 5, axis=0)
s0

[array([[[ 0.42711362,  2.13059943,  1.00668329, -1.16284069],
         [-2.35899144, -0.80764104,  0.30297251,  0.48409107],
         [-0.26014634,  0.82748868, -0.8690082 ,  1.4246587 ]]]),
 array([[[ 2.58018343,  1.37196985,  0.41966824, -0.65883572],
         [ 1.15267943,  0.93067746,  0.35353256,  1.71039414],
         [ 0.37644574,  0.21687124, -1.55216387, -0.27160831]]]),
 array([[[ 1.58161786, -0.81689155, -2.38956119, -1.0290985 ],
         [ 0.53990218, -0.46179142, -2.3284667 ,  1.03600742],
         [-0.15247791, -0.46434394, -0.96841871,  2.21144516]]]),
 array([[[-1.07131578,  0.07473873,  0.06633345, -0.45480478],
         [-1.36677173,  0.03374325,  0.87855698,  0.96613826],
         [ 0.55155076,  1.39285747,  0.31524593, -2.47357217]]]),
 array([[[ 0.05988685, -0.30591724,  0.41864608,  0.08106728],
         [-0.54590614, -0.75059878, -0.25141236, -2.21965157],
         [ 1.0724355 ,  0.19341328, -1.08585181, -1.38498778]]])]

In [88]:
type(s0)

list

In [89]:
s0[1]

array([[[ 2.58018343,  1.37196985,  0.41966824, -0.65883572],
        [ 1.15267943,  0.93067746,  0.35353256,  1.71039414],
        [ 0.37644574,  0.21687124, -1.55216387, -0.27160831]]])

In [90]:
s0[1].shape

(1, 3, 4)

In [92]:
s1 = np.split(before_split, 3, axis=1)
s1

[array([[[ 0.42711362,  2.13059943,  1.00668329, -1.16284069]],
 
        [[ 2.58018343,  1.37196985,  0.41966824, -0.65883572]],
 
        [[ 1.58161786, -0.81689155, -2.38956119, -1.0290985 ]],
 
        [[-1.07131578,  0.07473873,  0.06633345, -0.45480478]],
 
        [[ 0.05988685, -0.30591724,  0.41864608,  0.08106728]]]),
 array([[[-2.35899144, -0.80764104,  0.30297251,  0.48409107]],
 
        [[ 1.15267943,  0.93067746,  0.35353256,  1.71039414]],
 
        [[ 0.53990218, -0.46179142, -2.3284667 ,  1.03600742]],
 
        [[-1.36677173,  0.03374325,  0.87855698,  0.96613826]],
 
        [[-0.54590614, -0.75059878, -0.25141236, -2.21965157]]]),
 array([[[-0.26014634,  0.82748868, -0.8690082 ,  1.4246587 ]],
 
        [[ 0.37644574,  0.21687124, -1.55216387, -0.27160831]],
 
        [[-0.15247791, -0.46434394, -0.96841871,  2.21144516]],
 
        [[ 0.55155076,  1.39285747,  0.31524593, -2.47357217]],
 
        [[ 1.0724355 ,  0.19341328, -1.08585181, -1.38498778]]])]

In [93]:
s2 = np.split(before_split, 4, axis=2)
s2

[array([[[ 0.42711362],
         [-2.35899144],
         [-0.26014634]],
 
        [[ 2.58018343],
         [ 1.15267943],
         [ 0.37644574]],
 
        [[ 1.58161786],
         [ 0.53990218],
         [-0.15247791]],
 
        [[-1.07131578],
         [-1.36677173],
         [ 0.55155076]],
 
        [[ 0.05988685],
         [-0.54590614],
         [ 1.0724355 ]]]), array([[[ 2.13059943],
         [-0.80764104],
         [ 0.82748868]],
 
        [[ 1.37196985],
         [ 0.93067746],
         [ 0.21687124]],
 
        [[-0.81689155],
         [-0.46179142],
         [-0.46434394]],
 
        [[ 0.07473873],
         [ 0.03374325],
         [ 1.39285747]],
 
        [[-0.30591724],
         [-0.75059878],
         [ 0.19341328]]]), array([[[ 1.00668329],
         [ 0.30297251],
         [-0.8690082 ]],
 
        [[ 0.41966824],
         [ 0.35353256],
         [-1.55216387]],
 
        [[-2.38956119],
         [-2.3284667 ],
         [-0.96841871]],
 
        [[ 0.06633345],
   

## Array shape manipulation
### reshape

In [94]:
my_start_array = np.array(np.arange(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [95]:
my_start_array.shape

(24,)

In [96]:
my_3_8_array = my_start_array.reshape((3, 8))
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [97]:
my_3_8_array[0, 0] = 1234
my_start_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [98]:
# reshape created a view of the original array

In [99]:
my_ravel_array = my_3_8_array.ravel()
my_ravel_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [100]:
my_ravel_array.shape

(24,)

In [101]:
for n in my_3_8_array.flat:
    print(n)

1234
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## Rearrange array elements

In [102]:
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_start_array.reshape((2, 3, 4))

In [103]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [104]:
np.fliplr(my_3_8_array)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [105]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [106]:
np.fliplr(my_2_3_4_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [107]:
np.flipud(my_3_8_array)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [108]:
np.flipud(my_2_3_4_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [109]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [110]:
np.roll(my_start_array, 5)

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [111]:
np.roll(my_start_array, -5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23,  0,  1,  2,  3,  4])

In [113]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [114]:
np.roll(my_2_3_4_array, 2)

array([[[22, 23,  0,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]]])

In [115]:
np.roll(my_2_3_4_array, -2)

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23,  0,  1]]])

In [116]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [117]:
np.rot90(my_3_8_array )

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [118]:
np.rot90(my_3_8_array, k=-1)

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])

## Transpose like operation

In [119]:
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_start_array.reshape((2, 3, 4))

In [120]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [121]:
np.transpose(my_start_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [122]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [123]:
np.transpose(my_3_8_array)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [124]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [125]:
np.transpose(my_2_3_4_array, axes=(0,2,1))

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [126]:
np.swapaxes(my_2_3_4_array, 1, 0)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [127]:
np.rollaxis(my_2_3_4_array, 0, 2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

* Use `np.transpose` to permute all the axes one
* Use `np.swapaxes` to swap any two axes
* Use `np.rollaxis` to "rotate" the axes

## Tiling arrays

In [128]:
my_start_array = np.array(np.arange(12))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [129]:
np.tile(my_start_array, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [130]:
np.tile(my_start_array, 3).reshape((3, 12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [131]:
my_second_array = np.array(np.arange(7))
my_second_array

array([0, 1, 2, 3, 4, 5, 6])

In [132]:
tile_1 = np.tile(my_second_array, (3, 1))
tile_1

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [133]:
tile_2 = np.tile(tile_1, (2, 2))
tile_2

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

In [135]:
tile_3 = np.tile(tile_2, (3, 1))
tile_3

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

In [136]:
my_second_array

array([0, 1, 2, 3, 4, 5, 6])

In [137]:
np.repeat(my_second_array, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [138]:
my_repeatable_array = np.array(np.arange(24)).reshape(2,3,4)
my_repeatable_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [139]:
np.repeat(my_repeatable_array, 2, axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [140]:
np.repeat(my_repeatable_array, 2, axis=1)

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [20, 21, 22, 23]]])

In [141]:
np.repeat(my_repeatable_array, 2, axis=2)

array([[[ 0,  0,  1,  1,  2,  2,  3,  3],
        [ 4,  4,  5,  5,  6,  6,  7,  7],
        [ 8,  8,  9,  9, 10, 10, 11, 11]],

       [[12, 12, 13, 13, 14, 14, 15, 15],
        [16, 16, 17, 17, 18, 18, 19, 19],
        [20, 20, 21, 21, 22, 22, 23, 23]]])